# config.yaml: Model Training Pipeline Configuration

data:
  path: 'src/data/balanced_dataset_20250728.csv'
  schema:
    - name: 'text'
      type: 'str'
    - name: 'intent'
      type: 'str'
    - name: 'confidence'
      type: 'float'
    - name: 'timestamp'
      type: 'str'
    - name: 'text_length'
      type: 'int'
    - name: 'word_count'
      type: 'int'
    - name: 'has_personal_info'
      type: 'bool'
    - name: 'formality_score'
      type: 'float'
    - name: 'urgency_score'
      type: 'float'
    - name: 'embeddings'
      type: 'list[float]'
  stratify: true
  test_size: 0.2
  random_state: 42

preprocessing:
  embedding_model: 'all-MiniLM-L6-v2'
  balance: true
  balance_method: 'SMOTE'

model:
  type: 'LogisticRegression'
  hyperparameters:
    penalty: 'l2'  # Changed from l1 to l2 for better convergence
    C: 1.0  # Reduced from 10 for more regularization
    solver: 'lbfgs'  # Changed from liblinear to lbfgs (better for l2)
    max_iter: 1000  # Increased from default 100
    random_state: 42
  grid_search: true
  search_method: 'random'  # Options: 'grid', 'random', 'none'
  n_iter: 20  # Number of iterations for random search
  cross_val: false
  cv_folds: 5
  scoring: 'f1_weighted'  # Updated for multi-class classification

output:
  predictions: 'output/test_predictions.parquet'
  metrics: 'output/test_metrics.json'
  monitoring_log: 'logs/test_monitoring.jsonl'

logging:
  level: 'INFO' 