apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: ml-pipeline
  labels:
    app: ml-pipeline
    component: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-pipeline
  template:
    metadata:
      labels:
        app: ml-pipeline
        component: training
    spec:
      serviceAccountName: ml-pipeline-sa
      containers:
      - name: ml-pipeline
        image: your-registry/ml-pipeline:latest  # Replace with your image
        imagePullPolicy: Always
        env:
        - name: PYTHONPATH
          value: "/app/src"
        - name: PIPELINE_CONFIG
          value: "/app/config/config.yaml"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/credentials/gcs-key.json"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: credentials-volume
          mountPath: /app/credentials
        - name: data-volume
          mountPath: /app/data
        - name: models-volume
          mountPath: /app/models
        - name: output-volume
          mountPath: /app/output
        - name: logs-volume
          mountPath: /app/logs
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: ml-pipeline-config
      - name: credentials-volume
        secret:
          secretName: ml-pipeline-secrets
      - name: data-volume
        persistentVolumeClaim:
          claimName: ml-pipeline-data
      - name: models-volume
        persistentVolumeClaim:
          claimName: ml-pipeline-models
      - name: output-volume
        persistentVolumeClaim:
          claimName: ml-pipeline-output
      - name: logs-volume
        persistentVolumeClaim:
          claimName: ml-pipeline-logs
