apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline-sa
  namespace: ml-pipeline
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR-AWS-ACCOUNT:role/ml-pipeline-role  # Replace with your IAM role ARN
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ml-pipeline-role
  namespace: ml-pipeline
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ml-pipeline-rolebinding
  namespace: ml-pipeline
subjects:
- kind: ServiceAccount
  name: ml-pipeline-sa
  namespace: ml-pipeline
roleRef:
  kind: Role
  name: ml-pipeline-role
  apiGroup: rbac.authorization.k8s.io
